### ISSUE TITLE
Documentation for older releases 

### ISSUE THREAD

**Issue by prateekbhatt** [funcool/buddy-hashers#8]
Is there a way to read the documentation for older releases e.g.  0.7.0 ?

This might be less of an issue and more of a suggestion.

I am not able to use the current release (0.9.0) of buddy, because another library that I am using (clj-oauth) uses a older version of `org.bouncycastle/bcprov-jdk15on` "1.50" , instead of "1.5.4" that buddy 0.9.0 needs for the Blake2 hash function. So, I have to make do with 0.7.0 release of buddy. However, while browsing the documentation e.g. https://funcool.github.io/buddy-hashers/latest/ , I cannot find a way to get the docs for older releases.

**Comment by niwinz** [comment]
Hmm, as fast workaround you can checkout to the 0.7.0 tag and compile the documentation, or just read the .adoc file that is fairly readable.

Having old documentation is also good idea, thanks.

Furthermore, bouncy castle releases are mostly (or completly) backward compatible, so I recommend just force to use the 1.54 for all. I'm pretty sure that clj-oauth will work without issues with 1.54 ;)

**Comment by prateekbhatt** [comment]
Thanks, I read the buddy source code, and it was straightforward to figure out things :)

Closing this issue.
